# config.yaml
defaults:
  - dataset: default

dataset:
  _target_: data.Dataset
  N: 10
  min: -1
  max: 1

model:
  _target_: model.PolynomialModel
  n: 1000

loss:
  _target_: loss.total_loss
  alpha: 0.0

optimizer:
  _target_: torch.optim.SGD
  lr: 0.01

trainer:
  epochs: 1000
